english_to_french = [
    ("I am cold", "J'ai froid"),
    ("You are tired", "Tu es fatigué"),
    ("He is hungry", "Il a faim"),
    ("She is happy", "Elle est heureuse"),
    ("We are friends", "Nous sommes amis"),
    ("They are students", "Ils sont étudiants"),
    ("The cat is sleeping", "Le chat dort"),
    ("The sun is shining", "Le soleil brille"),
    ("We love music", "Nous aimons la musique"),
    ("She speaks French fluently", "Elle parle français couramment"),
    ("He enjoys reading books", "Il aime lire des livres"),
    ("They play soccer every weekend", "Ils jouent au football chaque week-end"),
    ("The movie starts at 7 PM", "Le film commence à 19 heures"),
    ("She wears a red dress", "Elle porte une robe rouge"),
    ("We cook dinner together", "Nous cuisinons le dîner ensemble"),
    ("He drives a blue car", "Il conduit une voiture bleue"),
    ("They visit museums often", "Ils visitent souvent des musées"),
    ("The restaurant serves delicious food", "Le restaurant sert une délicieuse cuisine"),
    ("She studies mathematics at university", "Elle étudie les mathématiques à l'université"),
    ("We watch movies on Fridays", "Nous regardons des films le vendredi"),
    ("He listens to music while jogging", "Il écoute de la musique en faisant du jogging"),
    ("They travel around the world", "Ils voyagent autour du monde"),
    ("The book is on the table", "Le livre est sur la table"),
    ("She dances gracefully", "Elle danse avec grâce"),
    ("We celebrate birthdays with cake", "Nous célébrons les anniversaires avec un gâteau"),
    ("He works hard every day", "Il travaille dur tous les jours"),
    ("They speak different languages", "Ils parlent différentes langues"),
    ("The flowers bloom in spring", "Les fleurs fleurissent au printemps"),
    ("She writes poetry in her free time", "Elle écrit de la poésie pendant son temps libre"),
    ("We learn something new every day", "Nous apprenons quelque chose de nouveau chaque jour"),
    ("The dog barks loudly", "Le chien aboie bruyamment"),
    ("He sings beautifully", "Il chante magnifiquement"),
    ("They swim in the pool", "Ils nagent dans la piscine"),
    ("The birds chirp in the morning", "Les oiseaux gazouillent le matin"),
    ("She teaches English at school", "Elle enseigne l'anglais à l'école"),
    ("We eat breakfast together", "Nous prenons le petit déjeuner ensemble"),
    ("He paints landscapes", "Il peint des paysages"),
    ("They laugh at the joke", "Ils rient de la blague"),
    ("The clock ticks loudly", "L'horloge tic-tac bruyamment"),
    ("She runs in the park", "Elle court dans le parc"),
    ("We travel by train", "Nous voyageons en train"),
    ("He writes a letter", "Il écrit une lettre"),
    ("They read books at the library", "Ils lisent des livres à la bibliothèque"),
    ("The baby cries", "Le bébé pleure"),
    ("She studies hard for exams", "Elle étudie dur pour les examens"),
    ("We plant flowers in the garden", "Nous plantons des fleurs dans le jardin"),
    ("He fixes the car", "Il répare la voiture"),
    ("They drink coffee in the morning", "Ils boivent du café le matin"),
    ("The sun sets in the evening", "Le soleil se couche le soir"),
    ("She dances at the party", "Elle danse à la fête"),
    ("We play music at the concert", "Nous jouons de la musique au concert"),
    ("He cooks dinner for his family", "Il cuisine le dîner pour sa famille"),
    ("They study French grammar", "Ils étudient la grammaire française"),
    ("The rain falls gently", "La pluie tombe doucement"),
    ("She sings a song", "Elle chante une chanson"),
    ("We watch a movie together", "Nous regardons un film ensemble"),
    ("He sleeps deeply", "Il dort profondément"),
    ("They travel to Paris", "Ils voyagent à Paris"),
    ("The children play in the park", "Les enfants jouent dans le parc"),
    ("She walks along the beach", "Elle se promène le long de la plage"),
    ("We talk on the phone", "Nous parlons au téléphone"),
    ("He waits for the bus", "Il attend le bus"),
    ("They visit the Eiffel Tower", "Ils visitent la tour Eiffel"),
    ("The stars twinkle at night", "Les étoiles scintillent la nuit"),
    ("She dreams of flying", "Elle rêve de voler"),
    ("We work in the office", "Nous travaillons au bureau"),
    ("He studies history", "Il étudie l'histoire"),
    ("They listen to the radio", "Ils écoutent la radio"),
    ("The wind blows gently", "Le vent souffle doucement"),
    ("She swims in the ocean", "Elle nage dans l'océan"),
    ("We dance at the wedding", "Nous dansons au mariage"),
    ("He climbs the mountain", "Il gravit la montagne"),
    ("They hike in the forest", "Ils font de la randonnée dans la forêt"),
    ("The cat meows loudly", "Le chat miaule bruyamment"),
    ("She paints a picture", "Elle peint un tableau"),
    ("We build a sandcastle", "Nous construisons un château de sable"),
    ("He sings in the choir", "Il chante dans le chœur"),
    ("They ride bicycles", "Ils font du vélo"),
    ("The coffee is hot", "Le café est chaud"),
    ("She wears glasses", "Elle porte des lunettes"),
    ("We visit our grandparents", "Nous rendons visite à nos grands-parents"),
    ("He plays the guitar", "Il joue de la guitare"),
    ("They go shopping", "Ils font du shopping"),
    ("The teacher explains the lesson", "Le professeur explique la leçon"),
    ("She takes the train to work", "Elle prend le train pour aller au travail"),
    ("We bake cookies", "Nous faisons des biscuits"),
    ("He washes his hands", "Il se lave les mains"),
    ("They enjoy the sunset", "Ils apprécient le coucher du soleil"),
    ("The river flows calmly", "La rivière coule calmement"),
    ("She feeds the cat", "Elle nourrit le chat"),
    ("We visit the museum", "Nous visitons le musée"),
    ("He fixes his bicycle", "Il répare son vélo"),
    ("They paint the walls", "Ils peignent les murs"),
    ("The baby sleeps peacefully", "Le bébé dort paisiblement"),
    ("She ties her shoelaces", "Elle attache ses lacets"),
    ("We climb the stairs", "Nous montons les escaliers"),
    ("He shaves in the morning", "Il se rase le matin"),
    ("They set the table", "Ils mettent la table"),
    ("The airplane takes off", "L'avion décolle"),
    ("She waters the plants", "Elle arrose les plantes"),
    ("We practice yoga", "Nous pratiquons le yoga"),
    ("He turns off the light", "Il éteint la lumière"),
    ("They play video games", "Ils jouent aux jeux vidéo"),
    ("The soup smells delicious", "La soupe sent délicieusement bon"),
    ("She locks the door", "Elle ferme la porte à clé"),
    ("We enjoy a picnic", "Nous profitons d'un pique-nique"),
    ("He checks his email", "Il vérifie ses emails"),
    ("They go to the gym", "Ils vont à la salle de sport"),
    ("The moon shines brightly", "La lune brille intensément"),
    ("She catches the bus", "Elle attrape le bus"),
    ("We greet our neighbors", "Nous saluons nos voisins"),
    ("He combs his hair", "Il se peigne les cheveux"),
    ("They wave goodbye", "Ils font un signe d'adieu"),
    ("I drink coffee in the morning", "Je bois du café le matin"),
    ("The book is on the chair", "Le livre est sur la chaise"),
]

english_to_french_qualitative = [
    ("He is cold", "Il a froid"),
    ("She is tired", "Elle est fatigué"),
    ("They are friends", "Ils sont amis"),
    ("They play soccer", "Ils jouent au football"),
    ("We watch movies", "Nous regardons des films"),
    ("He listens to music", "Il écoute de la musique"),
    ("She writes poetry", "Elle écrit de la poésie"),
    ("We learn something new", "nous apprenons quelque chose de nouveau"),
    ("The dog barks", "Le chien aboie"),
    ("She sings beautifully", "Elle chante magnifiquement"),
    ("They swim in the ocean", "Ils nagent dans l'océan"),
    ("The birds chirp", "Les oiseaux gazouillent"),
    ("She teaches English", "Elle enseigne l'anglais"),
    ("We eat breakfast", "Nous prenons le petit déjeuner"),
    ("She paints landscapes", "Elle peint des paysages"),
    ("They laugh at the movie", "Ils rient du film"),
    ("The clock ticks", "L'horloge tic-tac"),
    ("He runs in the park", "Il court dans le parc"),
    ("They travel by train", "Ils voyagent en train"),
    ("She writes a letter", "Elle écrit une lettre"),
    ("They read books", "Ils lisent des livres"),
    ("The baby cries loudly", "Le bébé pleure bruyamment"),
    ("She studies for exams", "Elle étudie pour les examens"),
    ("We plant flowers", "Nous plantons des fleurs"),
    ("He fixes a car", "Il répare une voiture"),
    ("They drink coffee", "Ils boivent du café"),
    ("The sun sets", "Le soleil se couche"),
    ("He dances at the party", "Il danse à la fête"),
    ("We play music", "Nous jouons de la musique"),
    ("He cooks dinner", "Il cuisine le dîner"),
    ("They study French", "Ils étudient français"),
    ("The rain falls", "La pluie tombe"),
    ("He sings a song", "Il chante une chanson"),
    ("We watch a movie", "Nous regardons un film"),
    ("She sleeps deeply", "Elle dort profondément"),
    ("We travel to Paris", "Nous voyageons à Paris"),
    ("The children play", "Les enfants jouent"),
    ("He walks along the beach", "Il se promène le long de la plage"),
    ("I talk on the phone", "Je parle au téléphone"),
    ("She waits for the bus", "Elle attend le bus"),
    ("We visit the Eiffel Tower", "Nous visitons la tour Eiffel"),
    ("The stars twinkle", "Les étoiles scintillent"),
    ("He dreams of flying", "Il rêve de voler"),
    ("She works hard every day", "Elle travaille dur tous les jours"),
    ("She studies history", "Elle étudie l'histoire"),
    ("She listens to the radio", "Elle écoute la radio"),
    ("The wind blows", "Le vent souffle"),
    ("She swims in the pool", "Elle nage dans la piscine"),
    ("We climb the mountain", "Nous montons la montagne"),
    ("The cat meows", "Le chat miaule"),
    ("He paints a picture", "Il peint un tableau"),
    ("We build a sandcastle together", "Nous construisons un château de sable ensemble"),
    ("She sings in the choir", "Elle chante dans le chœur"),
    ("They ride bicycles together", "Ils font du vélo ensemble"),
    ("The car is blue", "La voiture est bleue"),
    ("He wears glasses", "Il porte des lunettes"),
    ("We visit our grandparents together", "Nous rendons visite à nos grands-parents ensemble"),
    ("She plays the guitar", "Elle joue de la guitare"),
    ("They go shopping together", "Ils font du shopping ensemble"),
    ("She explains the lesson", "Elle explique la leçon"),
    ("She takes the train", "Elle prend le train"),
    ("They bake cookies", "Ils font des biscuits"),
    ("She washes her hands", "Elle se lave les mains"),
    ("They enjoy the sunset together", "Ils apprécient le coucher du soleil ensemble"),
    ("The river flows", "La rivière coule"),
    ("He feeds the cat", "Il nourrit le chat"),
    ("We visit the museum often", "Nous visitons le musée souvent"),
    ("She fixes her bicycle", "Elle répare son vélo"),
    ("They paint the walls together", "Ils peignent les murs ensemble"),
    ("The baby sleeps deeply", "Le bébé dort profondément"),
    ("He ties his shoelaces", "Il attache ses lacets"),
    ("She shaves in the morning", "Elle se rase le matin"),
    ("They set the table together", "Ils mettent la table ensemble"),
    ("The airplane takes off at 7 PM", "L'avion décolle à 19 heures"),
    ("He waters the plants", "Il arrose les plantes"),
    ("We practice yoga together", "Nous pratiquons le yoga ensemble"),
    ("She turns off the light", "Elle éteint la lumière"),
    ("We play video games", "Nous jouons aux jeux vidéo"),
    ("He locks the door", "Il ferme la porte à clé"),
    ("We enjoy a picnic together", "Nous profitons d'un pique-nique ensemble"),
    ("She checks her email", "Elle vérifie ses emails"),
    ("They go to the gym together", "Ils vont à la salle de sport ensemble"),
    ("The moon shines", "La lune brille"),
    ("He catches the bus", "Il attrape le bus"),
    ("We greet our neighbors together", "Nous saluons nos voisins ensemble"),
    ("She combs her hair", "Elle se peigne les cheveux"),
    ("They wave goodbye together", "Ils font un signe d'adieu ensemble"),
    ("I drink coffee in the evening", "Je bois du café le soir"),
    ("You are happy", "Tu es heureuse"),
    ("He enjoys reading", "Il aime lire"),
    ("They play soccer every day", "Ils jouent au football tous les jours"),
    ("The movie starts", "Le film commence"),
    ("He wears a red dress", "Il porte une robe rouge"),
    ("We cook dinner", "Nous cuisinons le dîner"),
    ("She drives a blue car", "Elle conduit une voiture bleue"),
    ("They visit museums", "Ils visitent des musées"),
    ("The restaurant serves food", "Le restaurant sert une cuisine"),
    ("She studies mathematics", "Elle étudie les mathématiques"),
    ("We watch movies on Fridays together", "Nous regardons des films le vendredi ensemble"),
    ("They travel around the world", "Ils voyagent autour du monde"),
    ("The table is in the library", "La table est à la bibliothèque"),
    ("He dances gracefully", "Il danse avec grâce"),
    ("He speaks different languages", "Il parle différentes langues"),
    ("The flowers bloom", "Les fleurs fleurissent"),
    ("He writes poetry in his free time", "Il écrit de la poésie pendant son temps libre"),
    ("I drink coffee", "Je bois du café"),
    ("You are hungry", "Tu a faim"),
    ("He drives a car", "Il conduit une voiture")
]
